alert("Namaste")
let age= prompt("What's your age?")
alert("Your age " + age + " is approximately " + 365*age + " days..")
alert("I have a project to find area of a rectangle and triangle..Help me..")
let length= prompt("What's the length of your rectangle..?")
let breadth= prompt("What's the breadth..?")
alert("The area of the rectangle is " + length*breadth + " .")
let base= prompt("What's the base of your rectangle..?")
let height= prompt("What's the height of your triangle..?")
alert("The area of the triangle is " + 1/2*base*height + " .")
console.log("The user's age is ", age )
console.log("The user's age in days are approximately ",365*age )
console.log("The length of rectangle is ", length, "and breadth is ", breadth)
console.log("The base of triangle is ", base, " and height is ", height)
console.log("The area of Rectangle is ", length*breadth)
console.log("The area of Rectangle is ", 1/2*base*height )
