alert("Namaste")
let name= prompt("What's your first name?")
let last= prompt("What's your last name?")
alert("Hey " + name  + " " + last + " there..!" )
let c= prompt("What's your class..?")
let age= prompt("What's your age")
let hobby= prompt("What are your hobbies..?")
console.log("Your full name is ", name, last)
console.log("You are in grade ", c)
console.log("Your age is " ,age)
console.log("Your hobbies are ", hobby)
